"""Unified Triality Pipeline (UTP) - Error Mitigation Layer Module: Minimum
Weight Perfect Matching (MWPM) Syndrome Decoder Loop
Reference: UTP-SPEC-2026-V6.0 (Section 4.2 & 13)

This module handles the active syndrome decoding processing loop. It ingests
binary syndrome vector arrays generated by the rotated surface code lattice
stabilizers and returns the targeted restorative Pauli correction instructions
needed to shield the network.

[UPGRADED 2026-10-05] The previous revision used a shared-stabilizer
intersection heuristic (mislabeled MWPM). It is replaced by an exact
single-error table-lookup decoder built from this package's own stabilizer
geometry (RotatedSurfaceCodeLattice: vertex Z1..Z4, plaquette X1..X4).
Verified: every one of the 9 data qubits has a unique non-zero syndrome
under each stabilizer type, so for single-qubit errors the table lookup IS
the minimum-weight perfect matching solution. Multi-error syndromes absent
from the table return no correction (the fault is counted downstream, not
hidden). Public interface unchanged: class name, constructor signature,
decode_syndrome_vectors(), and process_closed_loop_stabilization() keep
their names, arguments, and return shapes.
"""
import numpy as np
from typing import Dict, List, Tuple


class MinimumWeightPerfectMatchingDecoder:
    # Stabilizer geometry mirrors RotatedSurfaceCodeLattice in
    # triality_pipeline/error_mitigation/stabilizers.py.
    # Z-type (vertex) stabilizers detect X errors (bit-flips).
    VERTEX_STABILIZERS: Dict[str, Tuple[int, ...]] = {
        "Z1": (0, 1, 3, 4),
        "Z2": (1, 2, 4, 5),
        "Z3": (3, 4, 6, 7),
        "Z4": (4, 5, 7, 8),
    }
    # X-type (plaquette) stabilizers detect Z errors (phase-flips).
    PLAQUETTE_STABILIZERS: Dict[str, Tuple[int, ...]] = {
        "X1": (0, 3, 1, 4),
        "X2": (1, 4, 2, 5),
        "X3": (3, 6, 4, 7),
        "X4": (4, 7, 5, 8),
    }

    def __init__(self, lattice_distance: int = 3):
        """Initializes the MWPM active decoder loop module."""
        self.d = lattice_distance
        self.num_stabilizers = 4
        self._z_names = list(self.VERTEX_STABILIZERS.keys())
        self._x_names = list(self.PLAQUETTE_STABILIZERS.keys())
        # Exact MWPM for single-qubit errors: syndrome -> qubit.
        self._x_table = self._build_correction_table(self.VERTEX_STABILIZERS,
                                                     self._z_names)
        self._z_table = self._build_correction_table(
            self.PLAQUETTE_STABILIZERS, self._x_names)

    @staticmethod
    def _build_correction_table(stabilizers: Dict[str, Tuple[int, ...]],
                                names: List[str]) -> Dict[Tuple[int, ...], int]:
        table: Dict[Tuple[int, ...], int] = {(0,) * len(names): -1}
        for q in range(9):
            syn = tuple(1 if q in stabilizers[nm] else 0 for nm in names)
            # Unique single-error syndromes verified 2026-10-05; setdefault
            # keeps the first (lowest-index) qubit on any future collision.
            table.setdefault(syn, q)
        return table

    def _lookup(self, syndromes: List[int],
                table: Dict[Tuple[int, ...], int]) -> List[int]:
        key = tuple(int(v) for v in syndromes)
        qubit = table.get(key, -1)
        return [qubit] if qubit >= 0 else []

    def decode_syndrome_vectors(self, z_syndromes: List[int],
                                x_syndromes: List[int]) -> Dict[str, List[int]]:
        """Ingests raw binary syndrome vectors and returns the exact
        minimum-weight restorative corrections.

        z_syndromes: vertex (Z-type) syndromes -> X-error corrections.
        x_syndromes: plaquette (X-type) syndromes -> Z-error corrections.
        """
        corrections_to_apply = {"apply_x_restore": self._lookup(z_syndromes,
                                                                self._x_table),
                                "apply_z_restore": self._lookup(x_syndromes,
                                                                self._z_table)}
        return corrections_to_apply

    def process_closed_loop_stabilization(self, simulated_z_syndrome: List[int],
                                          simulated_x_syndrome: List[int]) -> bool:
        restoration_plan = self.decode_syndrome_vectors(simulated_z_syndrome,
                                                         simulated_x_syndrome)
        return bool(len(restoration_plan["apply_x_restore"]) > 0 or
                    len(restoration_plan["apply_z_restore"]) > 0)


# ================================
# Operational Verification Routine
# ================================
if __name__ == "__main__":
    print("=" * 80)
    print("UTP DECODER MODULE: INITIALIZING ACTIVE MINIMUM WEIGHT PERFECT MATCHING LOOP")
    print("=" * 80)
    decoder = MinimumWeightPerfectMatchingDecoder(lattice_distance=3)
    mock_z_vector = [0, 0, 0, 0]
    mock_x_vector = [1, 1, 0, 0]
    print(f"Incoming Test Input Z-Syndrome Array : {mock_z_vector}")
    print(f"Incoming Test Input X-Syndrome Array : {mock_x_vector}")
    print("-" * 80)
    correction_plan = decoder.decode_syndrome_vectors(mock_z_vector, mock_x_vector)
    print("MWPM Calculated Resolution Profile:")
    print(f"  Targeted Pauli X Recovery Gate Nodes : {correction_plan['apply_x_restore']}")
    print(f"  Targeted Pauli Z Recovery Gate Nodes : {correction_plan['apply_z_restore']}")
    print("-" * 80)
    is_operational = decoder.process_closed_loop_stabilization(mock_z_vector, mock_x_vector)
    print(f"Decoder Close-Loop Diagnostic Verification Flag: {is_operational}")
    print("=" * 80)
    assert is_operational, "Decoder Core Failure: MWPM loop failed to map distinct targets."
    print("STATUS CHECK: Active MWPM error decoding architecture loop compiled with NO ERRORS.")
    print("=" * 80)
